'use strict';

//#region dependencies
const { Timer } = require('../../utilities.js');

const bot_config = require('../../../config.js');

const { CustomRichEmbed } = require('../../libs/CustomRichEmbed.js');
const { DisBotCommand,
        DisBotCommander } = require('../../libs/DisBotCommander.js');
const { logUserError } = require('../../libs/errors.js');
const { sendConfirmationMessage } = require('../../libs/messages.js');
const { botHasPermissionsInGuild } = require('../../libs/permissions.js');
//#endregion dependencies

const bot_common_name = bot_config.COMMON_NAME;

const bot_special_channels = bot_config.SPECIAL_CHANNELS;
const bot_special_channels_category_name = bot_special_channels.find(special_channel => special_channel.id === `SPECIAL_CHANNELS_CATEGORY`).name;

const bot_special_text_channels = bot_config.SPECIAL_CHANNELS.filter(special_channel => special_channel.type === 'text');

const bot_special_text_channels_names = bot_special_text_channels.map(special_channel => special_channel.name);

module.exports = new DisBotCommand({
    name: 'CREATE_SPECIAL_CHANNELS',
    category: `${DisBotCommander.categories.GUILD_SETTINGS}`,
    weight: 1,
    description: 'Creates special channels',
    aliases: ['create_special_channels'],
    access_level: DisBotCommand.access_levels.GUILD_ADMIN,
    async executor(Discord, client, message, opts={}) {
        if (!botHasPermissionsInGuild(message, ['MANAGE_CHANNELS'])) return;

        const confirmation_embed = new CustomRichEmbed({
            title: 'Do you want to create the following channels automatically!',
            description: `These channels are used for various logs generated by ${bot_common_name}!`,
            fields: [
                {
                    name: 'Category Channel',
                    value: `${bot_special_channels_category_name}`,
                }, {
                    name: 'Text Channels',
                    value: `${bot_special_text_channels_names.join('\n')}`,
                },
            ],
        });

        sendConfirmationMessage(message.author.id, message.channel.id, true, confirmation_embed, async () => {
            let success = true;
            const bot_message = await message.channel.send(new CustomRichEmbed({
                title: `Creating \`${bot_special_channels_category_name}\``,
            }));
            try {
                const created_category = await message.guild.channels.create(`${bot_special_channels_category_name}`, {type: 'category'});
                await Timer(2000); // prevent odd stuff from happening by waiting
                for (let special_text_channel_name of bot_special_text_channels_names) {
                    await Timer(1000);

                    await bot_message.edit(new CustomRichEmbed({
                        title: `Creating \`${special_text_channel_name}\``,
                    }));

                    const created_channel = await message.guild.channels.create(`${special_text_channel_name}`, {type: 'text'});
                    await created_channel.setParent(created_category);

                    await Timer(1000);
                }
                await Timer(2000);
            } catch (error) {
                success = false;
                logUserError(message, error);
            } finally {
                if (success) {
                    bot_message.edit(new CustomRichEmbed({
                        color: 0x00FF00,
                        title: `Successfully created all channels!`,
                    }));
                } else {
                    bot_message.edit(new CustomRichEmbed({
                        color: 0xFFFF00,
                        title: `A failure has occurred while creating channels!`,
                    }));
                }
            }
        }, () => {
            message.channel.send(new CustomRichEmbed({
                title: 'Canceled Creating Channels!',
            }));
        });
    },
});
