################################################################
##                   Copyright (c) MidSpike                   ##
################################################################

# https://docs.docker.com/compose/compose-file/

################################################################

services:
  iris-utilities:
    container_name: iris-utilities
    build:
      context: .
      target: runtime
    restart: unless-stopped
    env_file:
      - ./docker/iris-utilities/.env
    depends_on:
      database:
        condition: service_healthy
      lavalink:
        condition: service_healthy
      libre-translate:
        condition: service_started
    networks:
      - database
      - lavalink
      - libre-translate

  database:
    container_name: database
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: unless-stopped
    env_file:
      - ./docker/database/.env
    volumes:
      - type: bind
        source: ./docker/database/storage
        target: /var/lib/mongo
      - type: bind
        source: ./docker/database/mongod.conf
        target: /etc/mongod.conf
    networks:
      - database
    expose: # expose ports for other containers to connect to
      - 27017
    ports: # expose ports for the host to connect to
      - 27017:27017 # internal:external ports
    healthcheck:
      # check if mongodb is listening on port 27017
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 1
      start_period: 15s

  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink:4.0.0-alpine # pin the image version to Lavalink v4
    restart: unless-stopped
    env_file: # use environment variables to configure Lavalink
      - ./docker/lavalink/.env
    # volumes:
    #   - ./application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
    #   - ./plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    networks:
      - lavalink
    expose: # expose ports for other containers to connect to
      - 2333
    # ports: # expose ports for the host to connect to
    #   - 2333:2333 # internal:external ports
    healthcheck:
      # check if lavalink is listening on port 2333
      test: '[ "$(netstat -ltn | grep -c ":2333")" -ne 1 ] && exit 1 || exit 0'
      interval: 10s
      timeout: 5s
      retries: 1
      start_period: 15s

  libre-translate:
    container_name: libre-translate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    env_file:
      - ./docker/libre-translate/.env
    volumes:
      - type: bind
        source: ./docker/libre-translate/storage
        target: /home/libretranslate
    networks:
      - libre-translate
    expose: # expose ports for other containers to connect to
      - 7681
    # ports: # expose ports for the host to connect to
    #   - 7681:7681 # internal:external ports

################################################################

networks:
  database:
    name: database

  lavalink:
    name: lavalink

  libre-translate:
    name: libre-translate
