'use strict';

//#region local dependencies
const { Timer } = require('../../utilities.js');

const bot_config = require('../../config.json');

const { CustomRichEmbed } = require('../../src/CustomRichEmbed.js');
const { DisBotCommander, DisBotCommand } = require('../../src/DisBotCommander.js');
const { sendConfirmationEmbed } = require('../../src/messages.js');
const { botHasPermissionsInGuild } = require('../../src/permissions.js');
//#endregion local dependencies

const bot_special_channels_category_name = bot_config.special_channels.SPECIAL_CHANNELS_CATEGORY.public_name;

module.exports = new DisBotCommand({
    name:'CREATE_SPECIAL_CHANNELS',
    category:`${DisBotCommander.categories.GUILD_SETTINGS}`,
    description:'Creates special channels',
    aliases:['create_special_channels'],
    access_level:DisBotCommand.access_levels.GUILD_ADMIN,
    async executor(Discord, client, message, opts={}) {
        const { bot_special_text_channels } = opts;
        if (!botHasPermissionsInGuild(message, ['MANAGE_CHANNELS'])) return;
        const embed = new CustomRichEmbed({
            title:'Do you want to create the following channels automatically!',
            description:`These channels are used for various logs generated by ${bot_config.common_name}!`,
            fields:[
                {name:'Category Channel', value:`${bot_special_channels_category_name}`},
                {name:'Text Channels', value:`${bot_special_text_channels.join('\n')}`}
            ]
        });
        sendConfirmationEmbed(message.author.id, message.channel.id, true, embed, async () => {
            let success = true;
            const bot_message = await message.channel.send(new CustomRichEmbed({
                title:`Creating \`${bot_special_channels_category_name}\``
            }));
            try {
                const created_category = await message.guild.channels.create(`${bot_special_channels_category_name}`, {type:'category'});
                await Timer(2000);
                for (let special_text_channel_name of bot_special_text_channels) {
                    await Timer(1000);
                    await bot_message.edit(new CustomRichEmbed({
                        title:`Creating \`${special_text_channel_name}\``
                    }));
                    const created_channel = await message.guild.channels.create(`${special_text_channel_name}`, {type:'text'});
                    await created_channel.setParent(created_category);
                    await Timer(1000);
                }
                await Timer(2000);
            } catch {
                success = false;
            } finally {
                if (success) {
                    bot_message.edit(new CustomRichEmbed({
                        color:0x00FF00,
                        title:`Successfully Finished Creating Channels!`
                    }));
                } else {
                    bot_message.edit(new CustomRichEmbed({
                        color:0xFFFF00,
                        title:`Failed When Creating Channels!`
                    }));
                }
            }
        }, () => {
            message.channel.send(new CustomRichEmbed({
                title:'Canceled Creating Channels!'
            }));
        });
    },
});
